# 빌드 할 때에는 jdk 17버전을 사용하겠다.
FROM eclipse-temurin:17-jdk AS build

ARG EC2_HOST
ENV EC2_HOST=${EC2_HOST}

ARG EC2_HOST1
ENV EC2_HOST1=${EC2_HOST1}

ARG EC2_HOST2
ENV EC2_HOST2=${EC2_HOST2}

ARG EC2_USER
ENV EC2_USER=${EC2_USER}

ARG PSQL_PORT
ENV PSQL_PORT=${PSQL_PORT}

ARG PSQL_DATABASE
ENV PSQL_DATABASE=${PSQL_DATABASE}

ARG PSQL_USERNAME
ENV PSQL_USERNAME=${PSQL_USERNAME}

ARG PSQL_PASSWORD
ENV PSQL_PASSWORD=${PSQL_PASSWORD}

ARG REDIS_PORT
ENV REDIS_PORT=${REDIS_PORT}

ARG JWT_SECRET
ENV JWT_SECRET=${JWT_SECRET}

ARG AWS_ACCESS_KEY
ENV AWS_ACCESS_KEY=${AWS_ACCESS_KEY}

ARG AWS_SECRET_KEY
ENV AWS_SECRET_KEY=${AWS_SECRET_KEY}

ARG AWS_BUCKET_NAME
ENV AWS_BUCKET_NAME=${AWS_BUCKET_NAME}

ARG AWS_REGION
ENV AWS_REGION=${AWS_REGION}

ARG KAKAO_CLIENT_ID
ENV KAKAO_CLIENT_ID=${KAKAO_CLIENT_ID}

ARG KAKAO_CLIENT_SECRET
ENV KAKAO_CLIENT_SECRET=${KAKAO_CLIENT_SECRET}

ARG NAVER_CLIENT_ID
ENV NAVER_CLIENT_ID=${NAVER_CLIENT_ID}

ARG NAVER_CLIENT_SECRET
ENV NAVER_CLIENT_SECRET=${NAVER_CLIENT_SECRET}

ARG FACEBOOK_CLIENT_ID
ENV FACEBOOK_CLIENT_ID=${FACEBOOK_CLIENT_ID}

ARG FACEBOOK_CLIENT_SECRET
ENV FACEBOOK_CLIENT_SECRET=${FACEBOOK_CLIENT_SECRET}

ARG GOOGLE_CLIENT_ID
ENV GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}

ARG GOOGLE_CLIENT_SECRET
ENV GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}

ARG GOOGLE_MAPS_API_KEY
ENV GOOGLE_MAPS_API_KEY=${GOOGLE_MAPS_API_KEY}

ARG FASTAPI_BASE_URL
ENV FASTAPI_BASE_URL=${FASTAPI_BASE_URL}

ARG INTERNAL_AI_TOKEN
ENV INTERNAL_AI_TOKEN=${INTERNAL_AI_TOKEN}

ARG MAIL_PASSWORD
ENV MAIL_PASSWORD=${MAIL_PASSWORD}

ARG MAIL_USERNAME
ENV MAIL_USERNAME=${MAIL_USERNAME}

ARG MESSAGE_API_KEY
ENV MESSAGE_API_KEY=${MESSAGE_API_KEY}

ARG MESSAGE_API_SECRET
ENV MESSAGE_API_SECRET=${MESSAGE_API_SECRET}

ARG BOOTPAY_APPLICATION_ID
ENV BOOTPAY_APPLICATION_ID=${BOOTPAY_APPLICATION_ID}

ARG BOOTPAY_SECRET_KEY
ENV BOOTPAY_SECRET_KEY=${BOOTPAY_SECRET_KEY}



# 작업 디렉토리 설정
WORKDIR /app

# 프로젝트 루트에 있는 파일을 컨테이너 안으로 복사해서 넣기
COPY . .

# 빌드
RUN chmod +x ./gradlew && ./gradlew build

# 실행만 담당하는 jre 환경으로 설정한다.
FROM eclipse-temurin:17-jre

ENV TZ=Asia/Seoul

# JAR 파일 복사
COPY --from=build /app/build/libs/app-0.0.1-SNAPSHOT.jar app.jar

# 포트 오픈
EXPOSE 10000

# 실행 명령어
ENTRYPOINT ["java", "-jar", "app.jar"]